name: Build and Run Docker Backup

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v3

      - name: ğŸ³ Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: ğŸ› ï¸ Construir imagen Docker
        run: |
          cd docker-backup
          sudo docker build -t backup-script .

      - name: â–¶ï¸ Ejecutar contenedor de prueba
        run: |
          sudo docker run --rm backup-script
